blockExoticSubdeps: false

packages:
  - "packages/*"

allowBuilds:
  "@avail-project/ca-common": true
  "@avail-project/nexus-core": true
  "@avail-project/nexus-types": true
  bufferutil: true
  core-js: true
  esbuild: true
  keccak: true
  msgpackr-extract: true
  msw: true
  protobufjs: true
  secp256k1: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true

overrides:
  "@types/react": "19.1.2"
  "@types/react-dom": "19.1.2"
  "axios": ">=1.15.0"

minimumReleaseAgeExclude:
  - "@avail-project/ca-common@2.3.0"
  - "@posthog/core@1.30.6"
  - "@posthog/types@1.379.3"
  - posthog-js@1.379.3
  - '@avail-project/nexus-core@2.1.0'
