allowBuilds:
  "@avail-project/ca-common": true
  bufferutil: true
  core-js: true
  esbuild: true
  keccak: true
  msgpackr-extract: true
  msw: true
  protobufjs: true
  secp256k1: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
onlyBuiltDependencies:
  - "@avail-project/ca-common"
  - "@avail-project/nexus-core"

overrides:
  "@types/react": "19.1.2"
  "@types/react-dom": "19.1.2"
